# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: check-toml

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: pretty-format-yaml
    args:
    - --autofix
    - --preserve-quotes
    - --indent=2

- repo: local
  hooks:
  - id: mypy
    name: Validate types with MyPy
    entry: poetry run mypy
    language: system
    types: [python]
    pass_filenames: false
    args:
    - "portfolio_backend"

  - id: ruff
    name: ruff
    description: "Run 'ruff' for extremely fast Python linting"
    entry: poetry run ruff check --force-exclude
    language: python
    types_or: [python, pyi]
    args: [--config=pyproject.toml, --fix]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"

  - id: ruff-format
    name: ruff-format
    description: "Run 'ruff format' for extremely fast Python formatting"
    entry: poetry run ruff format --force-exclude
    language: python
    types_or: [python, pyi]
    args: [--config=pyproject.toml]
    require_serial: true
    additional_dependencies: []
    minimum_pre_commit_version: "2.9.2"
